### PR TITLE
Add link to sister communities.

### PR DESCRIPTION
**Pull request by msporny**
This is an attempt to create harmony between the various communities that are working on Self Sovereign Identity by specifically calling them out on the W3C CCG front page as "sister communities". We need to start **publicly messaging** that we support each other and value one another's contribution to the movement. This is a small step toward that process.

This PR adds sister organization logos and links to the front page of the W3C CCG to the following communities (in order of founding): IIW, RWoT, ID2020, and DIF.

Please :+1:  or :-1: this PR. 
Please DO NOT debate who contributed what or point fingers on who is not acknowledging whom.

/cc @identitywoman @csuwildcat @windley

### CODE REVIEW

**Comment by csuwildcat** [comment]
Np on the DIF end of things - we'll add pretty much whatever you'd like to the DIF site.

**Comment by msporny** [comment]
@csuwildcat wrote:
> Np on the DIF end of things - we'll add pretty much whatever you'd like to the DIF site.

Awesome, thanks Dan! 

The ask is that each community add the same logos and links on the W3C CCG site (you'll be able to more easily see them once the PR goes through).

To be clear, this is just me talking -- no community consensus yet, but I'd be very surprised if folks pushed back against this (and it would reveal some fairly negative bias if so).

**Comment by kimdhamilton** [comment]
I think this is an excellent idea! +1

**Comment by msporny** [comment]
Closing, this has been hanging out there for 2.5 years w/o a merge.

**Pull request closed without merging**
